// <auto-generated />
using System;
using DKCrm.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DKCrm.Server.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyEmployee", b =>
                {
                    b.Property<Guid>("CompaniesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeesId")
                        .HasColumnType("uuid");

                    b.HasKey("CompaniesId", "EmployeesId");

                    b.HasIndex("EmployeesId");

                    b.ToTable("CompanyEmployee");
                });

            modelBuilder.Entity("CompanyTagsCompany", b =>
                {
                    b.Property<Guid>("CompaniesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsCompaniesId")
                        .HasColumnType("uuid");

                    b.HasKey("CompaniesId", "TagsCompaniesId");

                    b.HasIndex("TagsCompaniesId");

                    b.ToTable("CompanyTagsCompany");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.AccessRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("AccessUsersToComponent")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("AccessedComponentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AccessRestrictions");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Home")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Region")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.BankDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BeneficiaryAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Inn")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("KorBeneficiaryAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Kpp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("BankDetails");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActualAddressId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Director")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EmailAdditional")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("FnsRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Inn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Kbk")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Kpp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneAdditional")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ActualAddressId");

                    b.HasIndex("CompanyTypeId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.CompanyComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateTimeUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FromUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsWarningComment")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyComments");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.CompanyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("CompanyTypes");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsOurEmployee")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Position")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.FnsRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("KPP")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LegalAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OKVED")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ORGN")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Revenue")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("FnsRequests");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.LogUsersVisitToCompanyComments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyOwnerCommentsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimeVisit")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("LogUsersVisitToCompanyComments");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.TagsCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("TagsCompanies");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CurrencyDictionary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Five")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("FiveLoverNominal")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("Male")
                        .HasColumnType("boolean");

                    b.Property<bool>("MaleLoverNominal")
                        .HasColumnType("boolean");

                    b.Property<string>("One")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("OneLoverNominal")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Two")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("TwoLoverNominal")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.ToTable("CurrencyDictionaries");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.InfoSetToImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DirectoryType")
                        .HasColumnType("integer");

                    b.Property<int>("ImageType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PathToFile")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PathToPreviewFile")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("InfoSetsToImages");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.InternalCompanyData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CurrencyPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("KeyFns")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LocalCurrency")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<double>("Nds")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("InternalCompanyData");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ApplicationOrderingProducts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyInn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DateTimeCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateTimeTake")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateTimeUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ExportedOrderId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("InWork")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MissingProductsInCatalog")
                        .HasMaxLength(2400)
                        .HasColumnType("character varying(2400)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TakerUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TakerUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExportedOrderId")
                        .IsUnique();

                    b.ToTable("ApplicationOrderingProducts");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ApplicationOrderingProductsProduct", b =>
                {
                    b.Property<Guid>("ApplicationOrderingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("ApplicationOrderingId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ApplicationOrderingProductsProducts", (string)null);
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.CommentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateTimeUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FromUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsWarningComment")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2400)
                        .HasColumnType("character varying(2400)");

                    b.HasKey("Id");

                    b.ToTable("CommentOrders");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ExportedOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("CompanyBuyerId")
                        .HasColumnType("uuid");

                    b.Property<double?>("CurrencyPercent")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("DateTimeCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateTimeUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("EmployeeBuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Images")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsAllProductsAreCollected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double?>("Nds")
                        .HasColumnType("double precision");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<bool>("OrderIsOver")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OurCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OurEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyBuyerId");

                    b.HasIndex("EmployeeBuyerId");

                    b.HasIndex("OurCompanyId");

                    b.HasIndex("OurEmployeeId");

                    b.ToTable("ExportedOrders");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ExportedOrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateTimeUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValueConstant")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ExportedOrderStatus");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ExportedOrderStatusExportedOrder", b =>
                {
                    b.Property<Guid>("ExportedOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExportedOrderStatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateTimeCreate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateTimeUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ExportedOrderId", "ExportedOrderStatusId");

                    b.HasIndex("ExportedOrderStatusId");

                    b.ToTable("ExportedOrderStatusExportedOrder", (string)null);
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ExportedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("DateTimeConversionCurrency")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateTimeUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ExportedOrderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxDaysForDeliveryPlaned")
                        .HasColumnType("integer");

                    b.Property<int?>("MinDaysForDeliveryPlaned")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PriceInBuyerCurrency")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceInTransactionCurrency")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceLocal")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExportedOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ExportedProducts");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ImportedOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CurrencyPercent")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("DateTimeCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateTimeUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("EmployeeSellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Images")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsAllProductsAreCollected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double?>("Nds")
                        .HasColumnType("double precision");

                    b.Property<string>("Number")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("OrderIsOver")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OurCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OurEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SellersCompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TransactionCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeSellerId");

                    b.HasIndex("OurCompanyId");

                    b.HasIndex("OurEmployeeId");

                    b.HasIndex("SellersCompanyId");

                    b.ToTable("ImportedOrders");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ImportedOrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateTimeUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValueConstant")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ImportedOrderStatus");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ImportedOrderStatusImportedOrder", b =>
                {
                    b.Property<Guid>("ImportedOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImportedOrderStatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateTimeCreate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateTimeUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ImportedOrderId", "ImportedOrderStatusId");

                    b.HasIndex("ImportedOrderStatusId");

                    b.ToTable("ImportedOrderStatusImportedOrder", (string)null);
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ImportedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateTimeConversionCurrency")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateTimeUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ImportedOrderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("PriceInSupplierCurrency")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceInTransactionCurrency")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceLocal")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TransactionCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ImportedOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ImportedProducts");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.InfoSetFromDocumentToOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("PathToFile")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<float>("StampPosition")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("DocumentsToOrder");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.LogUsersVisitToOrderComments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimeVisit")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("OrderOwnerCommentsId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("LogUsersVisitToOrderComments");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.PurchaseAtExport", b =>
                {
                    b.Property<Guid>("ExportedProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImportedProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("ExportedProductId", "ImportedProductId");

                    b.HasIndex("ImportedProductId");

                    b.ToTable("PurchaseAtExports", (string)null);
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.PurchaseAtStorage", b =>
                {
                    b.Property<Guid>("StorageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImportedProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("StorageId", "ImportedProductId");

                    b.HasIndex("ImportedProductId");

                    b.ToTable("PurchaseAtStorages", (string)null);
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.SoldFromStorage", b =>
                {
                    b.Property<Guid>("StorageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExportedProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("StorageId", "ExportedProductId");

                    b.HasIndex("ExportedProductId");

                    b.ToTable("SoldFromStorages", (string)null);
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.CategoryOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Measure")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryOptions");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DateDelivery")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateTimeCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateTimeUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateTimeUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DayToDelivery")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryOptionId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOptions");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.ProductsInStorage", b =>
                {
                    b.Property<Guid?>("StorageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("StorageId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductsInStorages", (string)null);
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.Storage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateTimeUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("CompanyEmployee", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyTagsCompany", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKCrm.Shared.Models.CompanyModels.TagsCompany", null)
                        .WithMany()
                        .HasForeignKey("TagsCompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.BankDetails", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Company", "Company")
                        .WithMany("BankDetails")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.Company", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.Address", "ActualAddress")
                        .WithMany()
                        .HasForeignKey("ActualAddressId");

                    b.HasOne("DKCrm.Shared.Models.CompanyModels.CompanyType", "CompanyType")
                        .WithMany("Companies")
                        .HasForeignKey("CompanyTypeId");

                    b.Navigation("ActualAddress");

                    b.Navigation("CompanyType");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.CompanyComment", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Company", "Company")
                        .WithMany("Comments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.FnsRequest", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Company", "Company")
                        .WithOne("FnsRequest")
                        .HasForeignKey("DKCrm.Shared.Models.CompanyModels.FnsRequest", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ApplicationOrderingProducts", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.OrderModels.ExportedOrder", "ExportedOrder")
                        .WithOne("ApplicationOrderingProducts")
                        .HasForeignKey("DKCrm.Shared.Models.OrderModels.ApplicationOrderingProducts", "ExportedOrderId");

                    b.Navigation("ExportedOrder");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ApplicationOrderingProductsProduct", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.OrderModels.ApplicationOrderingProducts", "ApplicationOrdering")
                        .WithMany("ApplicationOrderingProductProduct")
                        .HasForeignKey("ApplicationOrderingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKCrm.Shared.Models.Products.Product", "Product")
                        .WithMany("ApplicationOrderingProductProduct")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationOrdering");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ExportedOrder", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Company", "CompanyBuyer")
                        .WithMany("ExportedOrdersBuyerCompany")
                        .HasForeignKey("CompanyBuyerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Employee", "EmployeeBuyer")
                        .WithMany("ExportedOrdersBuyer")
                        .HasForeignKey("EmployeeBuyerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Company", "OurCompany")
                        .WithMany("ExportedOrdersOurCompany")
                        .HasForeignKey("OurCompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Employee", "OurEmployee")
                        .WithMany("ExportedOrdersOur")
                        .HasForeignKey("OurEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CompanyBuyer");

                    b.Navigation("EmployeeBuyer");

                    b.Navigation("OurCompany");

                    b.Navigation("OurEmployee");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ExportedOrderStatus", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.OrderModels.ExportedOrderStatus", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ExportedOrderStatusExportedOrder", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.OrderModels.ExportedOrder", "ExportedOrder")
                        .WithMany("ExportedOrderStatusExported")
                        .HasForeignKey("ExportedOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKCrm.Shared.Models.OrderModels.ExportedOrderStatus", "ExportedOrderStatus")
                        .WithMany("ExportedOrderStatusExported")
                        .HasForeignKey("ExportedOrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExportedOrder");

                    b.Navigation("ExportedOrderStatus");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ExportedProduct", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.OrderModels.ExportedOrder", "ExportedOrder")
                        .WithMany("ExportedProducts")
                        .HasForeignKey("ExportedOrderId");

                    b.HasOne("DKCrm.Shared.Models.Products.Product", "Product")
                        .WithMany("ExportedProducts")
                        .HasForeignKey("ProductId");

                    b.Navigation("ExportedOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ImportedOrder", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Employee", "EmployeeSeller")
                        .WithMany("ImportedOrdersSellers")
                        .HasForeignKey("EmployeeSellerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Company", "OurCompany")
                        .WithMany("ImportedOrdersOurCompany")
                        .HasForeignKey("OurCompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Employee", "OurEmployee")
                        .WithMany("ImportedOrdersOur")
                        .HasForeignKey("OurEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DKCrm.Shared.Models.CompanyModels.Company", "SellersCompany")
                        .WithMany("ImportedOrdersSellersCompany")
                        .HasForeignKey("SellersCompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EmployeeSeller");

                    b.Navigation("OurCompany");

                    b.Navigation("OurEmployee");

                    b.Navigation("SellersCompany");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ImportedOrderStatus", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.OrderModels.ImportedOrderStatus", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ImportedOrderStatusImportedOrder", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.OrderModels.ImportedOrder", "ImportedOrder")
                        .WithMany("ImportedOrderStatusImportedOrders")
                        .HasForeignKey("ImportedOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKCrm.Shared.Models.OrderModels.ImportedOrderStatus", "ImportedOrderStatus")
                        .WithMany("ImportedOrderStatusImportedOrders")
                        .HasForeignKey("ImportedOrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedOrder");

                    b.Navigation("ImportedOrderStatus");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ImportedProduct", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.OrderModels.ImportedOrder", "ImportedOrder")
                        .WithMany("ImportedProducts")
                        .HasForeignKey("ImportedOrderId");

                    b.HasOne("DKCrm.Shared.Models.Products.Product", "Product")
                        .WithMany("ImportedProducts")
                        .HasForeignKey("ProductId");

                    b.Navigation("ImportedOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.PurchaseAtExport", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.OrderModels.ExportedProduct", "ExportedProduct")
                        .WithMany("PurchaseAtExports")
                        .HasForeignKey("ExportedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKCrm.Shared.Models.OrderModels.ImportedProduct", "ImportedProduct")
                        .WithMany("PurchaseAtExportList")
                        .HasForeignKey("ImportedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExportedProduct");

                    b.Navigation("ImportedProduct");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.PurchaseAtStorage", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.OrderModels.ImportedProduct", "ImportedProduct")
                        .WithMany("PurchaseAtStorageList")
                        .HasForeignKey("ImportedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKCrm.Shared.Models.Products.Storage", "Storage")
                        .WithMany("PurchaseAtStorageList")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedProduct");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.SoldFromStorage", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.OrderModels.ExportedProduct", "ExportedProduct")
                        .WithMany("SoldFromStorage")
                        .HasForeignKey("ExportedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKCrm.Shared.Models.Products.Storage", "Storage")
                        .WithMany("SoldFromStorageList")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExportedProduct");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.Category", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.Products.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.CategoryOption", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.Products.Category", "Category")
                        .WithMany("CategoryOptions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.Product", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.Products.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId");

                    b.HasOne("DKCrm.Shared.Models.Products.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.ProductOption", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.Products.CategoryOption", "CategoryOption")
                        .WithMany("ProductOption")
                        .HasForeignKey("CategoryOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKCrm.Shared.Models.Products.Product", "Product")
                        .WithMany("ProductOption")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryOption");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.ProductsInStorage", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.Products.Product", "Product")
                        .WithMany("ProductsInStorage")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKCrm.Shared.Models.Products.Storage", "Storage")
                        .WithMany("ProductsInStorage")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.Storage", b =>
                {
                    b.HasOne("DKCrm.Shared.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.Company", b =>
                {
                    b.Navigation("BankDetails");

                    b.Navigation("Comments");

                    b.Navigation("ExportedOrdersBuyerCompany");

                    b.Navigation("ExportedOrdersOurCompany");

                    b.Navigation("FnsRequest");

                    b.Navigation("ImportedOrdersOurCompany");

                    b.Navigation("ImportedOrdersSellersCompany");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.CompanyType", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.CompanyModels.Employee", b =>
                {
                    b.Navigation("ExportedOrdersBuyer");

                    b.Navigation("ExportedOrdersOur");

                    b.Navigation("ImportedOrdersOur");

                    b.Navigation("ImportedOrdersSellers");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ApplicationOrderingProducts", b =>
                {
                    b.Navigation("ApplicationOrderingProductProduct");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ExportedOrder", b =>
                {
                    b.Navigation("ApplicationOrderingProducts");

                    b.Navigation("ExportedOrderStatusExported");

                    b.Navigation("ExportedProducts");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ExportedOrderStatus", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ExportedOrderStatusExported");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ExportedProduct", b =>
                {
                    b.Navigation("PurchaseAtExports");

                    b.Navigation("SoldFromStorage");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ImportedOrder", b =>
                {
                    b.Navigation("ImportedOrderStatusImportedOrders");

                    b.Navigation("ImportedProducts");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ImportedOrderStatus", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ImportedOrderStatusImportedOrders");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.OrderModels.ImportedProduct", b =>
                {
                    b.Navigation("PurchaseAtExportList");

                    b.Navigation("PurchaseAtStorageList");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.Category", b =>
                {
                    b.Navigation("CategoryOptions");

                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.CategoryOption", b =>
                {
                    b.Navigation("ProductOption");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.Product", b =>
                {
                    b.Navigation("ApplicationOrderingProductProduct");

                    b.Navigation("ExportedProducts");

                    b.Navigation("ImportedProducts");

                    b.Navigation("ProductOption");

                    b.Navigation("ProductsInStorage");
                });

            modelBuilder.Entity("DKCrm.Shared.Models.Products.Storage", b =>
                {
                    b.Navigation("ProductsInStorage");

                    b.Navigation("PurchaseAtStorageList");

                    b.Navigation("SoldFromStorageList");
                });
#pragma warning restore 612, 618
        }
    }
}
